### ISSUE TITLE
pem_read_bio_pubkey failed, started sometime after 1.4 series

### ISSUE THREAD

**Issue by boutell** [compwright/passport-saml-metadata#18] opened 2019-02-15 18:46 UTC
This morning I deployed an application that had been using passport-saml with passport-saml-metadata successfully. On deployment I began to see:

pem_read_bio_pubkey failed

The stack shows this is ultimately happening in `SAML.validateSignatureForCert`.

On a hunch, I downgraded `passport-saml-metadata` to 1.4.x, and everything worked fine with no other changes. I am pinning to that series for now.

The idP is running Shibboleth.

Let me know if there is anything else that would be particularly helpful that I might be able to supply.

**Comment by boutell** [comment] 2019-02-15 18:46
(Thanks for your work on this module! I appreciate it.)

**Comment by compwright** [comment] 2019-08-17 21:32
I'm gonna guess that this is due to a version difference in the xml-crypto library (0.10.1 -> 1.1.4) which is used by passport-saml. Perhaps the newer version is more strict and you had a self-signed cert, or something along those lines. If you can provide a copy of your metadata xml file, I can try to reproduce the issue. Or, if you want to take a stab at it, PRs are welcome.

I'll close this, feel free to re-open it if you can provide enough information to reproduce the issue.

Related: https://github.com/bergie/passport-saml/issues/185

**Closed by compwright** 2019-08-17 21:32 UTC

**Comment by mosen** [comment] 2019-12-03 09:59
I'm investigating this issue after receiving the same error using Azure AD against passport-saml. I realise this isnt the same project, but i thought this might help.

For anyone rediscovering this issue, it was the stupid effect of supplying a path to a certificate instead of the literal PEM certificate for signature verification.

crypto-xml simply assumes the path you supplied was part of a PEM cert and prepends ---BEGIN CERTIFICATE---.

I guess the downstream module author needs to do sanity checking on the supplied cert.
